version: "3.9"

services:
  web:
    build:
      context: ./gwent_info_api
    container_name: fastapi_app
    ports:
      - "8000:8000"
    env_file:
      - ./gwent_info_api/.env
    depends_on:
      - redis

  bot:
    build:
      context: ./bot
    container_name: telegram_bot
    command: ["python", "bot/main.py"]
    env_file:
      - ./bot/.env

  redis:
    image: redis:7
    container_name: redis_server
    ports:
      - "6379:6379"
